/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.modelo.dao;

import edu.co.sena.ejemplodao.modelo.dto.*;
import edu.co.sena.ejemplodao.modelo.exceptions.*;

public interface DomicilioProveeDao
{
	/** 
	 * Inserts a new row in the domicilio_provee table.
	 */
	public DomicilioProveePk insert(DomicilioProvee dto) throws DomicilioProveeDaoException;

	/** 
	 * Updates a single row in the domicilio_provee table.
	 */
	public void update(DomicilioProveePk pk, DomicilioProvee dto) throws DomicilioProveeDaoException;

	/** 
	 * Deletes a single row in the domicilio_provee table.
	 */
	public void delete(DomicilioProveePk pk) throws DomicilioProveeDaoException;

	/** 
	 * Returns the rows from the domicilio_provee table that matches the specified primary-key value.
	 */
	public DomicilioProvee findByPrimaryKey(DomicilioProveePk pk) throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the criteria 'PROVEEDOR_TIPO_DOCUMENTO_TIPO_DOCUMENTO = :proveedorTipoDocumentoTipoDocumento AND PROVEEDOR_NUM_DOCUMENTO = :proveedorNumDocumento'.
	 */
	public DomicilioProvee findByPrimaryKey(String proveedorTipoDocumentoTipoDocumento, String proveedorNumDocumento) throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the criteria ''.
	 */
	public DomicilioProvee[] findAll() throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the criteria 'MUNICIPIO_ID_MUNICIPIO = :municipioIdMunicipio'.
	 */
	public DomicilioProvee[] findByMunicipio(int municipioIdMunicipio) throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the criteria 'PROVEEDOR_TIPO_DOCUMENTO_TIPO_DOCUMENTO = :proveedorTipoDocumentoTipoDocumento AND PROVEEDOR_NUM_DOCUMENTO = :proveedorNumDocumento'.
	 */
	public DomicilioProvee[] findByProveedor(String proveedorTipoDocumentoTipoDocumento, String proveedorNumDocumento) throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the criteria 'DIRECCION = :direccion'.
	 */
	public DomicilioProvee[] findWhereDireccionEquals(String direccion) throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the criteria 'TELEFONO = :telefono'.
	 */
	public DomicilioProvee[] findWhereTelefonoEquals(String telefono) throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the criteria 'BARRIO = :barrio'.
	 */
	public DomicilioProvee[] findWhereBarrioEquals(String barrio) throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the criteria 'LOCALIDAD = :localidad'.
	 */
	public DomicilioProvee[] findWhereLocalidadEquals(String localidad) throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the criteria 'CORREO_POSTAL = :correoPostal'.
	 */
	public DomicilioProvee[] findWhereCorreoPostalEquals(String correoPostal) throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the criteria 'MUNICIPIO_ID_MUNICIPIO = :municipioIdMunicipio'.
	 */
	public DomicilioProvee[] findWhereMunicipioIdMunicipioEquals(int municipioIdMunicipio) throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the criteria 'PROVEEDOR_TIPO_DOCUMENTO_TIPO_DOCUMENTO = :proveedorTipoDocumentoTipoDocumento'.
	 */
	public DomicilioProvee[] findWhereProveedorTipoDocumentoTipoDocumentoEquals(String proveedorTipoDocumentoTipoDocumento) throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the criteria 'PROVEEDOR_NUM_DOCUMENTO = :proveedorNumDocumento'.
	 */
	public DomicilioProvee[] findWhereProveedorNumDocumentoEquals(String proveedorNumDocumento) throws DomicilioProveeDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the domicilio_provee table that match the specified arbitrary SQL statement
	 */
	public DomicilioProvee[] findByDynamicSelect(String sql, Object[] sqlParams) throws DomicilioProveeDaoException;

	/** 
	 * Returns all rows from the domicilio_provee table that match the specified arbitrary SQL statement
	 */
	public DomicilioProvee[] findByDynamicWhere(String sql, Object[] sqlParams) throws DomicilioProveeDaoException;

}
