/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.modelo.dto;

import edu.co.sena.ejemplodao.modelo.dao.*;
import edu.co.sena.ejemplodao.modelo.factory.*;
import edu.co.sena.ejemplodao.modelo.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Cuenta implements Serializable
{
	/** 
	 * This attribute maps to the column TIPO_DOCUMENTO_TIPO_DOCUMENTO in the cuenta table.
	 */
	protected String tipoDocumentoTipoDocumento;

	/** 
	 * This attribute maps to the column NUMERO_DOCUMENTO in the cuenta table.
	 */
	protected String numeroDocumento;

	/** 
	 * This attribute maps to the column PRIMER_NOMBRE in the cuenta table.
	 */
	protected String primerNombre;

	/** 
	 * This attribute maps to the column SEGUNRO_NOMBRE in the cuenta table.
	 */
	protected String segunroNombre;

	/** 
	 * This attribute maps to the column PRIMER_APELLIDO in the cuenta table.
	 */
	protected String primerApellido;

	/** 
	 * This attribute maps to the column SEGUNDO_APELLIDO in the cuenta table.
	 */
	protected String segundoApellido;

	/** 
	 * This attribute maps to the column USUARIO_ID_USUARIO in the cuenta table.
	 */
	protected String usuarioIdUsuario;

	/**
	 * Method 'Cuenta'
	 * 
	 */
	public Cuenta()
	{
	}

	/**
	 * Method 'getTipoDocumentoTipoDocumento'
	 * 
	 * @return String
	 */
	public String getTipoDocumentoTipoDocumento()
	{
		return tipoDocumentoTipoDocumento;
	}

	/**
	 * Method 'setTipoDocumentoTipoDocumento'
	 * 
	 * @param tipoDocumentoTipoDocumento
	 */
	public void setTipoDocumentoTipoDocumento(String tipoDocumentoTipoDocumento)
	{
		this.tipoDocumentoTipoDocumento = tipoDocumentoTipoDocumento;
	}

	/**
	 * Method 'getNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getNumeroDocumento()
	{
		return numeroDocumento;
	}

	/**
	 * Method 'setNumeroDocumento'
	 * 
	 * @param numeroDocumento
	 */
	public void setNumeroDocumento(String numeroDocumento)
	{
		this.numeroDocumento = numeroDocumento;
	}

	/**
	 * Method 'getPrimerNombre'
	 * 
	 * @return String
	 */
	public String getPrimerNombre()
	{
		return primerNombre;
	}

	/**
	 * Method 'setPrimerNombre'
	 * 
	 * @param primerNombre
	 */
	public void setPrimerNombre(String primerNombre)
	{
		this.primerNombre = primerNombre;
	}

	/**
	 * Method 'getSegunroNombre'
	 * 
	 * @return String
	 */
	public String getSegunroNombre()
	{
		return segunroNombre;
	}

	/**
	 * Method 'setSegunroNombre'
	 * 
	 * @param segunroNombre
	 */
	public void setSegunroNombre(String segunroNombre)
	{
		this.segunroNombre = segunroNombre;
	}

	/**
	 * Method 'getPrimerApellido'
	 * 
	 * @return String
	 */
	public String getPrimerApellido()
	{
		return primerApellido;
	}

	/**
	 * Method 'setPrimerApellido'
	 * 
	 * @param primerApellido
	 */
	public void setPrimerApellido(String primerApellido)
	{
		this.primerApellido = primerApellido;
	}

	/**
	 * Method 'getSegundoApellido'
	 * 
	 * @return String
	 */
	public String getSegundoApellido()
	{
		return segundoApellido;
	}

	/**
	 * Method 'setSegundoApellido'
	 * 
	 * @param segundoApellido
	 */
	public void setSegundoApellido(String segundoApellido)
	{
		this.segundoApellido = segundoApellido;
	}

	/**
	 * Method 'getUsuarioIdUsuario'
	 * 
	 * @return String
	 */
	public String getUsuarioIdUsuario()
	{
		return usuarioIdUsuario;
	}

	/**
	 * Method 'setUsuarioIdUsuario'
	 * 
	 * @param usuarioIdUsuario
	 */
	public void setUsuarioIdUsuario(String usuarioIdUsuario)
	{
		this.usuarioIdUsuario = usuarioIdUsuario;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Cuenta)) {
			return false;
		}
		
		final Cuenta _cast = (Cuenta) _other;
		if (tipoDocumentoTipoDocumento == null ? _cast.tipoDocumentoTipoDocumento != tipoDocumentoTipoDocumento : !tipoDocumentoTipoDocumento.equals( _cast.tipoDocumentoTipoDocumento )) {
			return false;
		}
		
		if (numeroDocumento == null ? _cast.numeroDocumento != numeroDocumento : !numeroDocumento.equals( _cast.numeroDocumento )) {
			return false;
		}
		
		if (primerNombre == null ? _cast.primerNombre != primerNombre : !primerNombre.equals( _cast.primerNombre )) {
			return false;
		}
		
		if (segunroNombre == null ? _cast.segunroNombre != segunroNombre : !segunroNombre.equals( _cast.segunroNombre )) {
			return false;
		}
		
		if (primerApellido == null ? _cast.primerApellido != primerApellido : !primerApellido.equals( _cast.primerApellido )) {
			return false;
		}
		
		if (segundoApellido == null ? _cast.segundoApellido != segundoApellido : !segundoApellido.equals( _cast.segundoApellido )) {
			return false;
		}
		
		if (usuarioIdUsuario == null ? _cast.usuarioIdUsuario != usuarioIdUsuario : !usuarioIdUsuario.equals( _cast.usuarioIdUsuario )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoDocumentoTipoDocumento != null) {
			_hashCode = 29 * _hashCode + tipoDocumentoTipoDocumento.hashCode();
		}
		
		if (numeroDocumento != null) {
			_hashCode = 29 * _hashCode + numeroDocumento.hashCode();
		}
		
		if (primerNombre != null) {
			_hashCode = 29 * _hashCode + primerNombre.hashCode();
		}
		
		if (segunroNombre != null) {
			_hashCode = 29 * _hashCode + segunroNombre.hashCode();
		}
		
		if (primerApellido != null) {
			_hashCode = 29 * _hashCode + primerApellido.hashCode();
		}
		
		if (segundoApellido != null) {
			_hashCode = 29 * _hashCode + segundoApellido.hashCode();
		}
		
		if (usuarioIdUsuario != null) {
			_hashCode = 29 * _hashCode + usuarioIdUsuario.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CuentaPk
	 */
	public CuentaPk createPk()
	{
		return new CuentaPk(tipoDocumentoTipoDocumento, numeroDocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.modelo.dto.Cuenta: " );
		ret.append( "tipoDocumentoTipoDocumento=" + tipoDocumentoTipoDocumento );
		ret.append( ", numeroDocumento=" + numeroDocumento );
		ret.append( ", primerNombre=" + primerNombre );
		ret.append( ", segunroNombre=" + segunroNombre );
		ret.append( ", primerApellido=" + primerApellido );
		ret.append( ", segundoApellido=" + segundoApellido );
		ret.append( ", usuarioIdUsuario=" + usuarioIdUsuario );
		return ret.toString();
	}

}
