/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.modelo.dto;

import edu.co.sena.ejemplodao.modelo.dao.*;
import edu.co.sena.ejemplodao.modelo.factory.*;
import edu.co.sena.ejemplodao.modelo.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class DomicilioProvee implements Serializable
{
	/** 
	 * This attribute maps to the column DIRECCION in the domicilio_provee table.
	 */
	protected String direccion;

	/** 
	 * This attribute maps to the column TELEFONO in the domicilio_provee table.
	 */
	protected String telefono;

	/** 
	 * This attribute maps to the column BARRIO in the domicilio_provee table.
	 */
	protected String barrio;

	/** 
	 * This attribute maps to the column LOCALIDAD in the domicilio_provee table.
	 */
	protected String localidad;

	/** 
	 * This attribute maps to the column CORREO_POSTAL in the domicilio_provee table.
	 */
	protected String correoPostal;

	/** 
	 * This attribute maps to the column MUNICIPIO_ID_MUNICIPIO in the domicilio_provee table.
	 */
	protected int municipioIdMunicipio;

	/** 
	 * This attribute maps to the column PROVEEDOR_TIPO_DOCUMENTO_TIPO_DOCUMENTO in the domicilio_provee table.
	 */
	protected String proveedorTipoDocumentoTipoDocumento;

	/** 
	 * This attribute maps to the column PROVEEDOR_NUM_DOCUMENTO in the domicilio_provee table.
	 */
	protected String proveedorNumDocumento;

	/**
	 * Method 'DomicilioProvee'
	 * 
	 */
	public DomicilioProvee()
	{
	}

	/**
	 * Method 'getDireccion'
	 * 
	 * @return String
	 */
	public String getDireccion()
	{
		return direccion;
	}

	/**
	 * Method 'setDireccion'
	 * 
	 * @param direccion
	 */
	public void setDireccion(String direccion)
	{
		this.direccion = direccion;
	}

	/**
	 * Method 'getTelefono'
	 * 
	 * @return String
	 */
	public String getTelefono()
	{
		return telefono;
	}

	/**
	 * Method 'setTelefono'
	 * 
	 * @param telefono
	 */
	public void setTelefono(String telefono)
	{
		this.telefono = telefono;
	}

	/**
	 * Method 'getBarrio'
	 * 
	 * @return String
	 */
	public String getBarrio()
	{
		return barrio;
	}

	/**
	 * Method 'setBarrio'
	 * 
	 * @param barrio
	 */
	public void setBarrio(String barrio)
	{
		this.barrio = barrio;
	}

	/**
	 * Method 'getLocalidad'
	 * 
	 * @return String
	 */
	public String getLocalidad()
	{
		return localidad;
	}

	/**
	 * Method 'setLocalidad'
	 * 
	 * @param localidad
	 */
	public void setLocalidad(String localidad)
	{
		this.localidad = localidad;
	}

	/**
	 * Method 'getCorreoPostal'
	 * 
	 * @return String
	 */
	public String getCorreoPostal()
	{
		return correoPostal;
	}

	/**
	 * Method 'setCorreoPostal'
	 * 
	 * @param correoPostal
	 */
	public void setCorreoPostal(String correoPostal)
	{
		this.correoPostal = correoPostal;
	}

	/**
	 * Method 'getMunicipioIdMunicipio'
	 * 
	 * @return int
	 */
	public int getMunicipioIdMunicipio()
	{
		return municipioIdMunicipio;
	}

	/**
	 * Method 'setMunicipioIdMunicipio'
	 * 
	 * @param municipioIdMunicipio
	 */
	public void setMunicipioIdMunicipio(int municipioIdMunicipio)
	{
		this.municipioIdMunicipio = municipioIdMunicipio;
	}

	/**
	 * Method 'getProveedorTipoDocumentoTipoDocumento'
	 * 
	 * @return String
	 */
	public String getProveedorTipoDocumentoTipoDocumento()
	{
		return proveedorTipoDocumentoTipoDocumento;
	}

	/**
	 * Method 'setProveedorTipoDocumentoTipoDocumento'
	 * 
	 * @param proveedorTipoDocumentoTipoDocumento
	 */
	public void setProveedorTipoDocumentoTipoDocumento(String proveedorTipoDocumentoTipoDocumento)
	{
		this.proveedorTipoDocumentoTipoDocumento = proveedorTipoDocumentoTipoDocumento;
	}

	/**
	 * Method 'getProveedorNumDocumento'
	 * 
	 * @return String
	 */
	public String getProveedorNumDocumento()
	{
		return proveedorNumDocumento;
	}

	/**
	 * Method 'setProveedorNumDocumento'
	 * 
	 * @param proveedorNumDocumento
	 */
	public void setProveedorNumDocumento(String proveedorNumDocumento)
	{
		this.proveedorNumDocumento = proveedorNumDocumento;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DomicilioProvee)) {
			return false;
		}
		
		final DomicilioProvee _cast = (DomicilioProvee) _other;
		if (direccion == null ? _cast.direccion != direccion : !direccion.equals( _cast.direccion )) {
			return false;
		}
		
		if (telefono == null ? _cast.telefono != telefono : !telefono.equals( _cast.telefono )) {
			return false;
		}
		
		if (barrio == null ? _cast.barrio != barrio : !barrio.equals( _cast.barrio )) {
			return false;
		}
		
		if (localidad == null ? _cast.localidad != localidad : !localidad.equals( _cast.localidad )) {
			return false;
		}
		
		if (correoPostal == null ? _cast.correoPostal != correoPostal : !correoPostal.equals( _cast.correoPostal )) {
			return false;
		}
		
		if (municipioIdMunicipio != _cast.municipioIdMunicipio) {
			return false;
		}
		
		if (proveedorTipoDocumentoTipoDocumento == null ? _cast.proveedorTipoDocumentoTipoDocumento != proveedorTipoDocumentoTipoDocumento : !proveedorTipoDocumentoTipoDocumento.equals( _cast.proveedorTipoDocumentoTipoDocumento )) {
			return false;
		}
		
		if (proveedorNumDocumento == null ? _cast.proveedorNumDocumento != proveedorNumDocumento : !proveedorNumDocumento.equals( _cast.proveedorNumDocumento )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (direccion != null) {
			_hashCode = 29 * _hashCode + direccion.hashCode();
		}
		
		if (telefono != null) {
			_hashCode = 29 * _hashCode + telefono.hashCode();
		}
		
		if (barrio != null) {
			_hashCode = 29 * _hashCode + barrio.hashCode();
		}
		
		if (localidad != null) {
			_hashCode = 29 * _hashCode + localidad.hashCode();
		}
		
		if (correoPostal != null) {
			_hashCode = 29 * _hashCode + correoPostal.hashCode();
		}
		
		_hashCode = 29 * _hashCode + municipioIdMunicipio;
		if (proveedorTipoDocumentoTipoDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorTipoDocumentoTipoDocumento.hashCode();
		}
		
		if (proveedorNumDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorNumDocumento.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DomicilioProveePk
	 */
	public DomicilioProveePk createPk()
	{
		return new DomicilioProveePk(proveedorTipoDocumentoTipoDocumento, proveedorNumDocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.modelo.dto.DomicilioProvee: " );
		ret.append( "direccion=" + direccion );
		ret.append( ", telefono=" + telefono );
		ret.append( ", barrio=" + barrio );
		ret.append( ", localidad=" + localidad );
		ret.append( ", correoPostal=" + correoPostal );
		ret.append( ", municipioIdMunicipio=" + municipioIdMunicipio );
		ret.append( ", proveedorTipoDocumentoTipoDocumento=" + proveedorTipoDocumentoTipoDocumento );
		ret.append( ", proveedorNumDocumento=" + proveedorNumDocumento );
		return ret.toString();
	}

}
