/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.modelo.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the domicilio_cuentas table.
 */
public class DomicilioCuentasPk implements Serializable
{
	protected String cuentaTipoDocumentoTipoDocumento;

	protected String cuentaNumeroDocumento;

	/** 
	 * Sets the value of cuentaTipoDocumentoTipoDocumento
	 */
	public void setCuentaTipoDocumentoTipoDocumento(String cuentaTipoDocumentoTipoDocumento)
	{
		this.cuentaTipoDocumentoTipoDocumento = cuentaTipoDocumentoTipoDocumento;
	}

	/** 
	 * Gets the value of cuentaTipoDocumentoTipoDocumento
	 */
	public String getCuentaTipoDocumentoTipoDocumento()
	{
		return cuentaTipoDocumentoTipoDocumento;
	}

	/** 
	 * Sets the value of cuentaNumeroDocumento
	 */
	public void setCuentaNumeroDocumento(String cuentaNumeroDocumento)
	{
		this.cuentaNumeroDocumento = cuentaNumeroDocumento;
	}

	/** 
	 * Gets the value of cuentaNumeroDocumento
	 */
	public String getCuentaNumeroDocumento()
	{
		return cuentaNumeroDocumento;
	}

	/**
	 * Method 'DomicilioCuentasPk'
	 * 
	 */
	public DomicilioCuentasPk()
	{
	}

	/**
	 * Method 'DomicilioCuentasPk'
	 * 
	 * @param cuentaTipoDocumentoTipoDocumento
	 * @param cuentaNumeroDocumento
	 */
	public DomicilioCuentasPk(final String cuentaTipoDocumentoTipoDocumento, final String cuentaNumeroDocumento)
	{
		this.cuentaTipoDocumentoTipoDocumento = cuentaTipoDocumentoTipoDocumento;
		this.cuentaNumeroDocumento = cuentaNumeroDocumento;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DomicilioCuentasPk)) {
			return false;
		}
		
		final DomicilioCuentasPk _cast = (DomicilioCuentasPk) _other;
		if (cuentaTipoDocumentoTipoDocumento == null ? _cast.cuentaTipoDocumentoTipoDocumento != cuentaTipoDocumentoTipoDocumento : !cuentaTipoDocumentoTipoDocumento.equals( _cast.cuentaTipoDocumentoTipoDocumento )) {
			return false;
		}
		
		if (cuentaNumeroDocumento == null ? _cast.cuentaNumeroDocumento != cuentaNumeroDocumento : !cuentaNumeroDocumento.equals( _cast.cuentaNumeroDocumento )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (cuentaTipoDocumentoTipoDocumento != null) {
			_hashCode = 29 * _hashCode + cuentaTipoDocumentoTipoDocumento.hashCode();
		}
		
		if (cuentaNumeroDocumento != null) {
			_hashCode = 29 * _hashCode + cuentaNumeroDocumento.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.modelo.dto.DomicilioCuentasPk: " );
		ret.append( "cuentaTipoDocumentoTipoDocumento=" + cuentaTipoDocumentoTipoDocumento );
		ret.append( ", cuentaNumeroDocumento=" + cuentaNumeroDocumento );
		return ret.toString();
	}

}
