/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.modelo.dto;

import edu.co.sena.ejemplodao.modelo.dao.*;
import edu.co.sena.ejemplodao.modelo.factory.*;
import edu.co.sena.ejemplodao.modelo.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Factura implements Serializable
{
	/** 
	 * This attribute maps to the column ID_FACTURA in the factura table.
	 */
	protected int idFactura;

	/** 
	 * This attribute maps to the column CUENTA_TIPO_DOCUMENTO_TIPO_DOCUMENTO in the factura table.
	 */
	protected String cuentaTipoDocumentoTipoDocumento;

	/** 
	 * This attribute maps to the column CUENTA_NUMERO_DOCUMENTO in the factura table.
	 */
	protected String cuentaNumeroDocumento;

	/** 
	 * This attribute maps to the column FECHA_FACTURA in the factura table.
	 */
	protected Date fechaFactura;

	/** 
	 * This attribute maps to the column FORMA_PAGO in the factura table.
	 */
	protected String formaPago;

	/** 
	 * This attribute maps to the column ESTADO in the factura table.
	 */
	protected String estado;

	/**
	 * Method 'Factura'
	 * 
	 */
	public Factura()
	{
	}

	/**
	 * Method 'getIdFactura'
	 * 
	 * @return int
	 */
	public int getIdFactura()
	{
		return idFactura;
	}

	/**
	 * Method 'setIdFactura'
	 * 
	 * @param idFactura
	 */
	public void setIdFactura(int idFactura)
	{
		this.idFactura = idFactura;
	}

	/**
	 * Method 'getCuentaTipoDocumentoTipoDocumento'
	 * 
	 * @return String
	 */
	public String getCuentaTipoDocumentoTipoDocumento()
	{
		return cuentaTipoDocumentoTipoDocumento;
	}

	/**
	 * Method 'setCuentaTipoDocumentoTipoDocumento'
	 * 
	 * @param cuentaTipoDocumentoTipoDocumento
	 */
	public void setCuentaTipoDocumentoTipoDocumento(String cuentaTipoDocumentoTipoDocumento)
	{
		this.cuentaTipoDocumentoTipoDocumento = cuentaTipoDocumentoTipoDocumento;
	}

	/**
	 * Method 'getCuentaNumeroDocumento'
	 * 
	 * @return String
	 */
	public String getCuentaNumeroDocumento()
	{
		return cuentaNumeroDocumento;
	}

	/**
	 * Method 'setCuentaNumeroDocumento'
	 * 
	 * @param cuentaNumeroDocumento
	 */
	public void setCuentaNumeroDocumento(String cuentaNumeroDocumento)
	{
		this.cuentaNumeroDocumento = cuentaNumeroDocumento;
	}

	/**
	 * Method 'getFechaFactura'
	 * 
	 * @return Date
	 */
	public Date getFechaFactura()
	{
		return fechaFactura;
	}

	/**
	 * Method 'setFechaFactura'
	 * 
	 * @param fechaFactura
	 */
	public void setFechaFactura(Date fechaFactura)
	{
		this.fechaFactura = fechaFactura;
	}

	/**
	 * Method 'getFormaPago'
	 * 
	 * @return String
	 */
	public String getFormaPago()
	{
		return formaPago;
	}

	/**
	 * Method 'setFormaPago'
	 * 
	 * @param formaPago
	 */
	public void setFormaPago(String formaPago)
	{
		this.formaPago = formaPago;
	}

	/**
	 * Method 'getEstado'
	 * 
	 * @return String
	 */
	public String getEstado()
	{
		return estado;
	}

	/**
	 * Method 'setEstado'
	 * 
	 * @param estado
	 */
	public void setEstado(String estado)
	{
		this.estado = estado;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Factura)) {
			return false;
		}
		
		final Factura _cast = (Factura) _other;
		if (idFactura != _cast.idFactura) {
			return false;
		}
		
		if (cuentaTipoDocumentoTipoDocumento == null ? _cast.cuentaTipoDocumentoTipoDocumento != cuentaTipoDocumentoTipoDocumento : !cuentaTipoDocumentoTipoDocumento.equals( _cast.cuentaTipoDocumentoTipoDocumento )) {
			return false;
		}
		
		if (cuentaNumeroDocumento == null ? _cast.cuentaNumeroDocumento != cuentaNumeroDocumento : !cuentaNumeroDocumento.equals( _cast.cuentaNumeroDocumento )) {
			return false;
		}
		
		if (fechaFactura == null ? _cast.fechaFactura != fechaFactura : !fechaFactura.equals( _cast.fechaFactura )) {
			return false;
		}
		
		if (formaPago == null ? _cast.formaPago != formaPago : !formaPago.equals( _cast.formaPago )) {
			return false;
		}
		
		if (estado == null ? _cast.estado != estado : !estado.equals( _cast.estado )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idFactura;
		if (cuentaTipoDocumentoTipoDocumento != null) {
			_hashCode = 29 * _hashCode + cuentaTipoDocumentoTipoDocumento.hashCode();
		}
		
		if (cuentaNumeroDocumento != null) {
			_hashCode = 29 * _hashCode + cuentaNumeroDocumento.hashCode();
		}
		
		if (fechaFactura != null) {
			_hashCode = 29 * _hashCode + fechaFactura.hashCode();
		}
		
		if (formaPago != null) {
			_hashCode = 29 * _hashCode + formaPago.hashCode();
		}
		
		if (estado != null) {
			_hashCode = 29 * _hashCode + estado.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return FacturaPk
	 */
	public FacturaPk createPk()
	{
		return new FacturaPk(idFactura);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.modelo.dto.Factura: " );
		ret.append( "idFactura=" + idFactura );
		ret.append( ", cuentaTipoDocumentoTipoDocumento=" + cuentaTipoDocumentoTipoDocumento );
		ret.append( ", cuentaNumeroDocumento=" + cuentaNumeroDocumento );
		ret.append( ", fechaFactura=" + fechaFactura );
		ret.append( ", formaPago=" + formaPago );
		ret.append( ", estado=" + estado );
		return ret.toString();
	}

}
