/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.modelo.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the inventario_compras table.
 */
public class InventarioComprasPk implements Serializable
{
	protected int idInventario;

	protected String productoIdProducto;

	protected String proveedorTipoDocumentoTipoDocumento;

	protected String proveedorNumDocumento;

	/** 
	 * This attribute represents whether the primitive attribute idInventario is null.
	 */
	protected boolean idInventarioNull;

	/** 
	 * Sets the value of idInventario
	 */
	public void setIdInventario(int idInventario)
	{
		this.idInventario = idInventario;
	}

	/** 
	 * Gets the value of idInventario
	 */
	public int getIdInventario()
	{
		return idInventario;
	}

	/** 
	 * Sets the value of productoIdProducto
	 */
	public void setProductoIdProducto(String productoIdProducto)
	{
		this.productoIdProducto = productoIdProducto;
	}

	/** 
	 * Gets the value of productoIdProducto
	 */
	public String getProductoIdProducto()
	{
		return productoIdProducto;
	}

	/** 
	 * Sets the value of proveedorTipoDocumentoTipoDocumento
	 */
	public void setProveedorTipoDocumentoTipoDocumento(String proveedorTipoDocumentoTipoDocumento)
	{
		this.proveedorTipoDocumentoTipoDocumento = proveedorTipoDocumentoTipoDocumento;
	}

	/** 
	 * Gets the value of proveedorTipoDocumentoTipoDocumento
	 */
	public String getProveedorTipoDocumentoTipoDocumento()
	{
		return proveedorTipoDocumentoTipoDocumento;
	}

	/** 
	 * Sets the value of proveedorNumDocumento
	 */
	public void setProveedorNumDocumento(String proveedorNumDocumento)
	{
		this.proveedorNumDocumento = proveedorNumDocumento;
	}

	/** 
	 * Gets the value of proveedorNumDocumento
	 */
	public String getProveedorNumDocumento()
	{
		return proveedorNumDocumento;
	}

	/**
	 * Method 'InventarioComprasPk'
	 * 
	 */
	public InventarioComprasPk()
	{
	}

	/**
	 * Method 'InventarioComprasPk'
	 * 
	 * @param idInventario
	 * @param productoIdProducto
	 * @param proveedorTipoDocumentoTipoDocumento
	 * @param proveedorNumDocumento
	 */
	public InventarioComprasPk(final int idInventario, final String productoIdProducto, final String proveedorTipoDocumentoTipoDocumento, final String proveedorNumDocumento)
	{
		this.idInventario = idInventario;
		this.productoIdProducto = productoIdProducto;
		this.proveedorTipoDocumentoTipoDocumento = proveedorTipoDocumentoTipoDocumento;
		this.proveedorNumDocumento = proveedorNumDocumento;
	}

	/** 
	 * Sets the value of idInventarioNull
	 */
	public void setIdInventarioNull(boolean idInventarioNull)
	{
		this.idInventarioNull = idInventarioNull;
	}

	/** 
	 * Gets the value of idInventarioNull
	 */
	public boolean isIdInventarioNull()
	{
		return idInventarioNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof InventarioComprasPk)) {
			return false;
		}
		
		final InventarioComprasPk _cast = (InventarioComprasPk) _other;
		if (idInventario != _cast.idInventario) {
			return false;
		}
		
		if (productoIdProducto == null ? _cast.productoIdProducto != productoIdProducto : !productoIdProducto.equals( _cast.productoIdProducto )) {
			return false;
		}
		
		if (proveedorTipoDocumentoTipoDocumento == null ? _cast.proveedorTipoDocumentoTipoDocumento != proveedorTipoDocumentoTipoDocumento : !proveedorTipoDocumentoTipoDocumento.equals( _cast.proveedorTipoDocumentoTipoDocumento )) {
			return false;
		}
		
		if (proveedorNumDocumento == null ? _cast.proveedorNumDocumento != proveedorNumDocumento : !proveedorNumDocumento.equals( _cast.proveedorNumDocumento )) {
			return false;
		}
		
		if (idInventarioNull != _cast.idInventarioNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idInventario;
		if (productoIdProducto != null) {
			_hashCode = 29 * _hashCode + productoIdProducto.hashCode();
		}
		
		if (proveedorTipoDocumentoTipoDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorTipoDocumentoTipoDocumento.hashCode();
		}
		
		if (proveedorNumDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorNumDocumento.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idInventarioNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.modelo.dto.InventarioComprasPk: " );
		ret.append( "idInventario=" + idInventario );
		ret.append( ", productoIdProducto=" + productoIdProducto );
		ret.append( ", proveedorTipoDocumentoTipoDocumento=" + proveedorTipoDocumentoTipoDocumento );
		ret.append( ", proveedorNumDocumento=" + proveedorNumDocumento );
		return ret.toString();
	}

}
