/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.modelo.dto;

import edu.co.sena.ejemplodao.modelo.dao.*;
import edu.co.sena.ejemplodao.modelo.factory.*;
import edu.co.sena.ejemplodao.modelo.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ItemCarrito implements Serializable
{
	/** 
	 * This attribute maps to the column CARRITO_COMPRAS_ID_CARRITO in the item_carrito table.
	 */
	protected String carritoComprasIdCarrito;

	/** 
	 * This attribute maps to the column PRODUCTO_ID_PRODUCTO in the item_carrito table.
	 */
	protected String productoIdProducto;

	/** 
	 * This attribute maps to the column CANTIDAD in the item_carrito table.
	 */
	protected int cantidad;

	/** 
	 * This attribute represents whether the primitive attribute cantidad is null.
	 */
	protected boolean cantidadNull = true;

	/** 
	 * This attribute maps to the column VALOR_UNITARIO in the item_carrito table.
	 */
	protected double valorUnitario;

	/** 
	 * This attribute represents whether the primitive attribute valorUnitario is null.
	 */
	protected boolean valorUnitarioNull = true;

	/** 
	 * This attribute maps to the column VALOR_TOTAL in the item_carrito table.
	 */
	protected double valorTotal;

	/** 
	 * This attribute represents whether the primitive attribute valorTotal is null.
	 */
	protected boolean valorTotalNull = true;

	/**
	 * Method 'ItemCarrito'
	 * 
	 */
	public ItemCarrito()
	{
	}

	/**
	 * Method 'getCarritoComprasIdCarrito'
	 * 
	 * @return String
	 */
	public String getCarritoComprasIdCarrito()
	{
		return carritoComprasIdCarrito;
	}

	/**
	 * Method 'setCarritoComprasIdCarrito'
	 * 
	 * @param carritoComprasIdCarrito
	 */
	public void setCarritoComprasIdCarrito(String carritoComprasIdCarrito)
	{
		this.carritoComprasIdCarrito = carritoComprasIdCarrito;
	}

	/**
	 * Method 'getProductoIdProducto'
	 * 
	 * @return String
	 */
	public String getProductoIdProducto()
	{
		return productoIdProducto;
	}

	/**
	 * Method 'setProductoIdProducto'
	 * 
	 * @param productoIdProducto
	 */
	public void setProductoIdProducto(String productoIdProducto)
	{
		this.productoIdProducto = productoIdProducto;
	}

	/**
	 * Method 'getCantidad'
	 * 
	 * @return int
	 */
	public int getCantidad()
	{
		return cantidad;
	}

	/**
	 * Method 'setCantidad'
	 * 
	 * @param cantidad
	 */
	public void setCantidad(int cantidad)
	{
		this.cantidad = cantidad;
		this.cantidadNull = false;
	}

	/**
	 * Method 'setCantidadNull'
	 * 
	 * @param value
	 */
	public void setCantidadNull(boolean value)
	{
		this.cantidadNull = value;
	}

	/**
	 * Method 'isCantidadNull'
	 * 
	 * @return boolean
	 */
	public boolean isCantidadNull()
	{
		return cantidadNull;
	}

	/**
	 * Method 'getValorUnitario'
	 * 
	 * @return double
	 */
	public double getValorUnitario()
	{
		return valorUnitario;
	}

	/**
	 * Method 'setValorUnitario'
	 * 
	 * @param valorUnitario
	 */
	public void setValorUnitario(double valorUnitario)
	{
		this.valorUnitario = valorUnitario;
		this.valorUnitarioNull = false;
	}

	/**
	 * Method 'setValorUnitarioNull'
	 * 
	 * @param value
	 */
	public void setValorUnitarioNull(boolean value)
	{
		this.valorUnitarioNull = value;
	}

	/**
	 * Method 'isValorUnitarioNull'
	 * 
	 * @return boolean
	 */
	public boolean isValorUnitarioNull()
	{
		return valorUnitarioNull;
	}

	/**
	 * Method 'getValorTotal'
	 * 
	 * @return double
	 */
	public double getValorTotal()
	{
		return valorTotal;
	}

	/**
	 * Method 'setValorTotal'
	 * 
	 * @param valorTotal
	 */
	public void setValorTotal(double valorTotal)
	{
		this.valorTotal = valorTotal;
		this.valorTotalNull = false;
	}

	/**
	 * Method 'setValorTotalNull'
	 * 
	 * @param value
	 */
	public void setValorTotalNull(boolean value)
	{
		this.valorTotalNull = value;
	}

	/**
	 * Method 'isValorTotalNull'
	 * 
	 * @return boolean
	 */
	public boolean isValorTotalNull()
	{
		return valorTotalNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ItemCarrito)) {
			return false;
		}
		
		final ItemCarrito _cast = (ItemCarrito) _other;
		if (carritoComprasIdCarrito == null ? _cast.carritoComprasIdCarrito != carritoComprasIdCarrito : !carritoComprasIdCarrito.equals( _cast.carritoComprasIdCarrito )) {
			return false;
		}
		
		if (productoIdProducto == null ? _cast.productoIdProducto != productoIdProducto : !productoIdProducto.equals( _cast.productoIdProducto )) {
			return false;
		}
		
		if (cantidad != _cast.cantidad) {
			return false;
		}
		
		if (cantidadNull != _cast.cantidadNull) {
			return false;
		}
		
		if (valorUnitario != _cast.valorUnitario) {
			return false;
		}
		
		if (valorUnitarioNull != _cast.valorUnitarioNull) {
			return false;
		}
		
		if (valorTotal != _cast.valorTotal) {
			return false;
		}
		
		if (valorTotalNull != _cast.valorTotalNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (carritoComprasIdCarrito != null) {
			_hashCode = 29 * _hashCode + carritoComprasIdCarrito.hashCode();
		}
		
		if (productoIdProducto != null) {
			_hashCode = 29 * _hashCode + productoIdProducto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + cantidad;
		_hashCode = 29 * _hashCode + (cantidadNull ? 1 : 0);
		long temp_valorUnitario = Double.doubleToLongBits(valorUnitario);
		_hashCode = 29 * _hashCode + (int) (temp_valorUnitario ^ (temp_valorUnitario >>> 32));
		_hashCode = 29 * _hashCode + (valorUnitarioNull ? 1 : 0);
		long temp_valorTotal = Double.doubleToLongBits(valorTotal);
		_hashCode = 29 * _hashCode + (int) (temp_valorTotal ^ (temp_valorTotal >>> 32));
		_hashCode = 29 * _hashCode + (valorTotalNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ItemCarritoPk
	 */
	public ItemCarritoPk createPk()
	{
		return new ItemCarritoPk(carritoComprasIdCarrito, productoIdProducto);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.modelo.dto.ItemCarrito: " );
		ret.append( "carritoComprasIdCarrito=" + carritoComprasIdCarrito );
		ret.append( ", productoIdProducto=" + productoIdProducto );
		ret.append( ", cantidad=" + cantidad );
		ret.append( ", valorUnitario=" + valorUnitario );
		ret.append( ", valorTotal=" + valorTotal );
		return ret.toString();
	}

}
