/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.modelo.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the pedido table.
 */
public class PedidoPk implements Serializable
{
	protected int facturaIdFactura;

	/** 
	 * This attribute represents whether the primitive attribute facturaIdFactura is null.
	 */
	protected boolean facturaIdFacturaNull;

	/** 
	 * Sets the value of facturaIdFactura
	 */
	public void setFacturaIdFactura(int facturaIdFactura)
	{
		this.facturaIdFactura = facturaIdFactura;
	}

	/** 
	 * Gets the value of facturaIdFactura
	 */
	public int getFacturaIdFactura()
	{
		return facturaIdFactura;
	}

	/**
	 * Method 'PedidoPk'
	 * 
	 */
	public PedidoPk()
	{
	}

	/**
	 * Method 'PedidoPk'
	 * 
	 * @param facturaIdFactura
	 */
	public PedidoPk(final int facturaIdFactura)
	{
		this.facturaIdFactura = facturaIdFactura;
	}

	/** 
	 * Sets the value of facturaIdFacturaNull
	 */
	public void setFacturaIdFacturaNull(boolean facturaIdFacturaNull)
	{
		this.facturaIdFacturaNull = facturaIdFacturaNull;
	}

	/** 
	 * Gets the value of facturaIdFacturaNull
	 */
	public boolean isFacturaIdFacturaNull()
	{
		return facturaIdFacturaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof PedidoPk)) {
			return false;
		}
		
		final PedidoPk _cast = (PedidoPk) _other;
		if (facturaIdFactura != _cast.facturaIdFactura) {
			return false;
		}
		
		if (facturaIdFacturaNull != _cast.facturaIdFacturaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + facturaIdFactura;
		_hashCode = 29 * _hashCode + (facturaIdFacturaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.modelo.dto.PedidoPk: " );
		ret.append( "facturaIdFactura=" + facturaIdFactura );
		return ret.toString();
	}

}
