/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.modelo.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the proveedor table.
 */
public class ProveedorPk implements Serializable
{
	protected String tipoDocumentoTipoDocumento;

	protected String numDocumento;

	/** 
	 * Sets the value of tipoDocumentoTipoDocumento
	 */
	public void setTipoDocumentoTipoDocumento(String tipoDocumentoTipoDocumento)
	{
		this.tipoDocumentoTipoDocumento = tipoDocumentoTipoDocumento;
	}

	/** 
	 * Gets the value of tipoDocumentoTipoDocumento
	 */
	public String getTipoDocumentoTipoDocumento()
	{
		return tipoDocumentoTipoDocumento;
	}

	/** 
	 * Sets the value of numDocumento
	 */
	public void setNumDocumento(String numDocumento)
	{
		this.numDocumento = numDocumento;
	}

	/** 
	 * Gets the value of numDocumento
	 */
	public String getNumDocumento()
	{
		return numDocumento;
	}

	/**
	 * Method 'ProveedorPk'
	 * 
	 */
	public ProveedorPk()
	{
	}

	/**
	 * Method 'ProveedorPk'
	 * 
	 * @param tipoDocumentoTipoDocumento
	 * @param numDocumento
	 */
	public ProveedorPk(final String tipoDocumentoTipoDocumento, final String numDocumento)
	{
		this.tipoDocumentoTipoDocumento = tipoDocumentoTipoDocumento;
		this.numDocumento = numDocumento;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ProveedorPk)) {
			return false;
		}
		
		final ProveedorPk _cast = (ProveedorPk) _other;
		if (tipoDocumentoTipoDocumento == null ? _cast.tipoDocumentoTipoDocumento != tipoDocumentoTipoDocumento : !tipoDocumentoTipoDocumento.equals( _cast.tipoDocumentoTipoDocumento )) {
			return false;
		}
		
		if (numDocumento == null ? _cast.numDocumento != numDocumento : !numDocumento.equals( _cast.numDocumento )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoDocumentoTipoDocumento != null) {
			_hashCode = 29 * _hashCode + tipoDocumentoTipoDocumento.hashCode();
		}
		
		if (numDocumento != null) {
			_hashCode = 29 * _hashCode + numDocumento.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.modelo.dto.ProveedorPk: " );
		ret.append( "tipoDocumentoTipoDocumento=" + tipoDocumentoTipoDocumento );
		ret.append( ", numDocumento=" + numDocumento );
		return ret.toString();
	}

}
