/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.modelo.dto;

import edu.co.sena.ejemplodao.modelo.dao.*;
import edu.co.sena.ejemplodao.modelo.factory.*;
import edu.co.sena.ejemplodao.modelo.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class TipoDocumento implements Serializable
{
	/** 
	 * This attribute maps to the column TIPO_DOCUMENTO in the tipo_documento table.
	 */
	protected String tipoDocumento;

	/** 
	 * This attribute maps to the column DESCRIPCION in the tipo_documento table.
	 */
	protected String descripcion;

	/**
	 * Method 'TipoDocumento'
	 * 
	 */
	public TipoDocumento()
	{
	}

	/**
	 * Method 'getTipoDocumento'
	 * 
	 * @return String
	 */
	public String getTipoDocumento()
	{
		return tipoDocumento;
	}

	/**
	 * Method 'setTipoDocumento'
	 * 
	 * @param tipoDocumento
	 */
	public void setTipoDocumento(String tipoDocumento)
	{
		this.tipoDocumento = tipoDocumento;
	}

	/**
	 * Method 'getDescripcion'
	 * 
	 * @return String
	 */
	public String getDescripcion()
	{
		return descripcion;
	}

	/**
	 * Method 'setDescripcion'
	 * 
	 * @param descripcion
	 */
	public void setDescripcion(String descripcion)
	{
		this.descripcion = descripcion;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof TipoDocumento)) {
			return false;
		}
		
		final TipoDocumento _cast = (TipoDocumento) _other;
		if (tipoDocumento == null ? _cast.tipoDocumento != tipoDocumento : !tipoDocumento.equals( _cast.tipoDocumento )) {
			return false;
		}
		
		if (descripcion == null ? _cast.descripcion != descripcion : !descripcion.equals( _cast.descripcion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoDocumento != null) {
			_hashCode = 29 * _hashCode + tipoDocumento.hashCode();
		}
		
		if (descripcion != null) {
			_hashCode = 29 * _hashCode + descripcion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TipoDocumentoPk
	 */
	public TipoDocumentoPk createPk()
	{
		return new TipoDocumentoPk(tipoDocumento);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.modelo.dto.TipoDocumento: " );
		ret.append( "tipoDocumento=" + tipoDocumento );
		ret.append( ", descripcion=" + descripcion );
		return ret.toString();
	}

}
