/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.modelo.jdbc;

import edu.co.sena.ejemplodao.modelo.dao.*;
import edu.co.sena.ejemplodao.modelo.factory.*;
import java.util.Date;
import edu.co.sena.ejemplodao.modelo.dto.*;
import edu.co.sena.ejemplodao.modelo.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class FacturaDaoImpl extends AbstractDAO implements FacturaDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT ID_FACTURA, CUENTA_TIPO_DOCUMENTO_TIPO_DOCUMENTO, CUENTA_NUMERO_DOCUMENTO, FECHA_FACTURA, FORMA_PAGO, ESTADO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( ID_FACTURA, CUENTA_TIPO_DOCUMENTO_TIPO_DOCUMENTO, CUENTA_NUMERO_DOCUMENTO, FECHA_FACTURA, FORMA_PAGO, ESTADO ) VALUES ( ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET ID_FACTURA = ?, CUENTA_TIPO_DOCUMENTO_TIPO_DOCUMENTO = ?, CUENTA_NUMERO_DOCUMENTO = ?, FECHA_FACTURA = ?, FORMA_PAGO = ?, ESTADO = ? WHERE ID_FACTURA = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE ID_FACTURA = ?";

	/** 
	 * Index of column ID_FACTURA
	 */
	protected static final int COLUMN_ID_FACTURA = 1;

	/** 
	 * Index of column CUENTA_TIPO_DOCUMENTO_TIPO_DOCUMENTO
	 */
	protected static final int COLUMN_CUENTA_TIPO_DOCUMENTO_TIPO_DOCUMENTO = 2;

	/** 
	 * Index of column CUENTA_NUMERO_DOCUMENTO
	 */
	protected static final int COLUMN_CUENTA_NUMERO_DOCUMENTO = 3;

	/** 
	 * Index of column FECHA_FACTURA
	 */
	protected static final int COLUMN_FECHA_FACTURA = 4;

	/** 
	 * Index of column FORMA_PAGO
	 */
	protected static final int COLUMN_FORMA_PAGO = 5;

	/** 
	 * Index of column ESTADO
	 */
	protected static final int COLUMN_ESTADO = 6;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 6;

	/** 
	 * Index of primary-key column ID_FACTURA
	 */
	protected static final int PK_COLUMN_ID_FACTURA = 1;

	/** 
	 * Inserts a new row in the factura table.
	 */
	public FacturaPk insert(Factura dto) throws FacturaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getIdFactura() );
			stmt.setString( index++, dto.getCuentaTipoDocumentoTipoDocumento() );
			stmt.setString( index++, dto.getCuentaNumeroDocumento() );
			stmt.setDate(index++, dto.getFechaFactura()==null ? null : new java.sql.Date( dto.getFechaFactura().getTime() ) );
			stmt.setString( index++, dto.getFormaPago() );
			stmt.setString( index++, dto.getEstado() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new FacturaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the factura table.
	 */
	public void update(FacturaPk pk, Factura dto) throws FacturaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdFactura() );
			stmt.setString( index++, dto.getCuentaTipoDocumentoTipoDocumento() );
			stmt.setString( index++, dto.getCuentaNumeroDocumento() );
			stmt.setDate(index++, dto.getFechaFactura()==null ? null : new java.sql.Date( dto.getFechaFactura().getTime() ) );
			stmt.setString( index++, dto.getFormaPago() );
			stmt.setString( index++, dto.getEstado() );
			stmt.setInt( 7, pk.getIdFactura() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new FacturaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the factura table.
	 */
	public void delete(FacturaPk pk) throws FacturaDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdFactura() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new FacturaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the factura table that matches the specified primary-key value.
	 */
	public Factura findByPrimaryKey(FacturaPk pk) throws FacturaDaoException
	{
		return findByPrimaryKey( pk.getIdFactura() );
	}

	/** 
	 * Returns all rows from the factura table that match the criteria 'ID_FACTURA = :idFactura'.
	 */
	public Factura findByPrimaryKey(int idFactura) throws FacturaDaoException
	{
		Factura ret[] = findByDynamicSelect( SQL_SELECT + " WHERE ID_FACTURA = ?", new Object[] {  new Integer(idFactura) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the factura table that match the criteria ''.
	 */
	public Factura[] findAll() throws FacturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY ID_FACTURA", null );
	}

	/** 
	 * Returns all rows from the factura table that match the criteria 'CUENTA_TIPO_DOCUMENTO_TIPO_DOCUMENTO = :cuentaTipoDocumentoTipoDocumento AND CUENTA_NUMERO_DOCUMENTO = :cuentaNumeroDocumento'.
	 */
	public Factura[] findByCuenta(String cuentaTipoDocumentoTipoDocumento, String cuentaNumeroDocumento) throws FacturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CUENTA_TIPO_DOCUMENTO_TIPO_DOCUMENTO = ? AND CUENTA_NUMERO_DOCUMENTO = ?", new Object[] { cuentaTipoDocumentoTipoDocumento, cuentaNumeroDocumento } );
	}

	/** 
	 * Returns all rows from the factura table that match the criteria 'ID_FACTURA = :idFactura'.
	 */
	public Factura[] findWhereIdFacturaEquals(int idFactura) throws FacturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ID_FACTURA = ? ORDER BY ID_FACTURA", new Object[] {  new Integer(idFactura) } );
	}

	/** 
	 * Returns all rows from the factura table that match the criteria 'CUENTA_TIPO_DOCUMENTO_TIPO_DOCUMENTO = :cuentaTipoDocumentoTipoDocumento'.
	 */
	public Factura[] findWhereCuentaTipoDocumentoTipoDocumentoEquals(String cuentaTipoDocumentoTipoDocumento) throws FacturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CUENTA_TIPO_DOCUMENTO_TIPO_DOCUMENTO = ? ORDER BY CUENTA_TIPO_DOCUMENTO_TIPO_DOCUMENTO", new Object[] { cuentaTipoDocumentoTipoDocumento } );
	}

	/** 
	 * Returns all rows from the factura table that match the criteria 'CUENTA_NUMERO_DOCUMENTO = :cuentaNumeroDocumento'.
	 */
	public Factura[] findWhereCuentaNumeroDocumentoEquals(String cuentaNumeroDocumento) throws FacturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CUENTA_NUMERO_DOCUMENTO = ? ORDER BY CUENTA_NUMERO_DOCUMENTO", new Object[] { cuentaNumeroDocumento } );
	}

	/** 
	 * Returns all rows from the factura table that match the criteria 'FECHA_FACTURA = :fechaFactura'.
	 */
	public Factura[] findWhereFechaFacturaEquals(Date fechaFactura) throws FacturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FECHA_FACTURA = ? ORDER BY FECHA_FACTURA", new Object[] { fechaFactura==null ? null : new java.sql.Date( fechaFactura.getTime() ) } );
	}

	/** 
	 * Returns all rows from the factura table that match the criteria 'FORMA_PAGO = :formaPago'.
	 */
	public Factura[] findWhereFormaPagoEquals(String formaPago) throws FacturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE FORMA_PAGO = ? ORDER BY FORMA_PAGO", new Object[] { formaPago } );
	}

	/** 
	 * Returns all rows from the factura table that match the criteria 'ESTADO = :estado'.
	 */
	public Factura[] findWhereEstadoEquals(String estado) throws FacturaDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE ESTADO = ? ORDER BY ESTADO", new Object[] { estado } );
	}

	/**
	 * Method 'FacturaDaoImpl'
	 * 
	 */
	public FacturaDaoImpl()
	{
	}

	/**
	 * Method 'FacturaDaoImpl'
	 * 
	 * @param userConn
	 */
	public FacturaDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "tienda_online2.factura";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Factura fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Factura dto = new Factura();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Factura[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Factura dto = new Factura();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Factura ret[] = new Factura[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Factura dto, ResultSet rs) throws SQLException
	{
		dto.setIdFactura( rs.getInt( COLUMN_ID_FACTURA ) );
		dto.setCuentaTipoDocumentoTipoDocumento( rs.getString( COLUMN_CUENTA_TIPO_DOCUMENTO_TIPO_DOCUMENTO ) );
		dto.setCuentaNumeroDocumento( rs.getString( COLUMN_CUENTA_NUMERO_DOCUMENTO ) );
		dto.setFechaFactura( rs.getDate(COLUMN_FECHA_FACTURA ) );
		dto.setFormaPago( rs.getString( COLUMN_FORMA_PAGO ) );
		dto.setEstado( rs.getString( COLUMN_ESTADO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Factura dto)
	{
	}

	/** 
	 * Returns all rows from the factura table that match the specified arbitrary SQL statement
	 */
	public Factura[] findByDynamicSelect(String sql, Object[] sqlParams) throws FacturaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new FacturaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the factura table that match the specified arbitrary SQL statement
	 */
	public Factura[] findByDynamicWhere(String sql, Object[] sqlParams) throws FacturaDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new FacturaDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
