/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.modelo.jdbc;

import edu.co.sena.ejemplodao.modelo.dao.*;
import edu.co.sena.ejemplodao.modelo.factory.*;
import edu.co.sena.ejemplodao.modelo.dto.*;
import edu.co.sena.ejemplodao.modelo.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class ProveedorDaoImpl extends AbstractDAO implements ProveedorDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT TIPO_DOCUMENTO_TIPO_DOCUMENTO, NUM_DOCUMENTO, NOMBRE_PROVEEDOR, CORREO FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( TIPO_DOCUMENTO_TIPO_DOCUMENTO, NUM_DOCUMENTO, NOMBRE_PROVEEDOR, CORREO ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET TIPO_DOCUMENTO_TIPO_DOCUMENTO = ?, NUM_DOCUMENTO = ?, NOMBRE_PROVEEDOR = ?, CORREO = ? WHERE TIPO_DOCUMENTO_TIPO_DOCUMENTO = ? AND NUM_DOCUMENTO = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE TIPO_DOCUMENTO_TIPO_DOCUMENTO = ? AND NUM_DOCUMENTO = ?";

	/** 
	 * Index of column TIPO_DOCUMENTO_TIPO_DOCUMENTO
	 */
	protected static final int COLUMN_TIPO_DOCUMENTO_TIPO_DOCUMENTO = 1;

	/** 
	 * Index of column NUM_DOCUMENTO
	 */
	protected static final int COLUMN_NUM_DOCUMENTO = 2;

	/** 
	 * Index of column NOMBRE_PROVEEDOR
	 */
	protected static final int COLUMN_NOMBRE_PROVEEDOR = 3;

	/** 
	 * Index of column CORREO
	 */
	protected static final int COLUMN_CORREO = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column TIPO_DOCUMENTO_TIPO_DOCUMENTO
	 */
	protected static final int PK_COLUMN_TIPO_DOCUMENTO_TIPO_DOCUMENTO = 1;

	/** 
	 * Index of primary-key column NUM_DOCUMENTO
	 */
	protected static final int PK_COLUMN_NUM_DOCUMENTO = 2;

	/** 
	 * Inserts a new row in the proveedor table.
	 */
	public ProveedorPk insert(Proveedor dto) throws ProveedorDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setString( index++, dto.getTipoDocumentoTipoDocumento() );
			stmt.setString( index++, dto.getNumDocumento() );
			stmt.setString( index++, dto.getNombreProveedor() );
			stmt.setString( index++, dto.getCorreo() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the proveedor table.
	 */
	public void update(ProveedorPk pk, Proveedor dto) throws ProveedorDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setString( index++, dto.getTipoDocumentoTipoDocumento() );
			stmt.setString( index++, dto.getNumDocumento() );
			stmt.setString( index++, dto.getNombreProveedor() );
			stmt.setString( index++, dto.getCorreo() );
			stmt.setString( 5, pk.getTipoDocumentoTipoDocumento() );
			stmt.setString( 6, pk.getNumDocumento() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the proveedor table.
	 */
	public void delete(ProveedorPk pk) throws ProveedorDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setString( 1, pk.getTipoDocumentoTipoDocumento() );
			stmt.setString( 2, pk.getNumDocumento() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the proveedor table that matches the specified primary-key value.
	 */
	public Proveedor findByPrimaryKey(ProveedorPk pk) throws ProveedorDaoException
	{
		return findByPrimaryKey( pk.getTipoDocumentoTipoDocumento(), pk.getNumDocumento() );
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'TIPO_DOCUMENTO_TIPO_DOCUMENTO = :tipoDocumentoTipoDocumento AND NUM_DOCUMENTO = :numDocumento'.
	 */
	public Proveedor findByPrimaryKey(String tipoDocumentoTipoDocumento, String numDocumento) throws ProveedorDaoException
	{
		Proveedor ret[] = findByDynamicSelect( SQL_SELECT + " WHERE TIPO_DOCUMENTO_TIPO_DOCUMENTO = ? AND NUM_DOCUMENTO = ?", new Object[] { tipoDocumentoTipoDocumento, numDocumento } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria ''.
	 */
	public Proveedor[] findAll() throws ProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY TIPO_DOCUMENTO_TIPO_DOCUMENTO, NUM_DOCUMENTO", null );
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'TIPO_DOCUMENTO_TIPO_DOCUMENTO = :tipoDocumentoTipoDocumento'.
	 */
	public Proveedor[] findByTipoDocumento(String tipoDocumentoTipoDocumento) throws ProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE TIPO_DOCUMENTO_TIPO_DOCUMENTO = ?", new Object[] { tipoDocumentoTipoDocumento } );
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'TIPO_DOCUMENTO_TIPO_DOCUMENTO = :tipoDocumentoTipoDocumento'.
	 */
	public Proveedor[] findWhereTipoDocumentoTipoDocumentoEquals(String tipoDocumentoTipoDocumento) throws ProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE TIPO_DOCUMENTO_TIPO_DOCUMENTO = ? ORDER BY TIPO_DOCUMENTO_TIPO_DOCUMENTO", new Object[] { tipoDocumentoTipoDocumento } );
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'NUM_DOCUMENTO = :numDocumento'.
	 */
	public Proveedor[] findWhereNumDocumentoEquals(String numDocumento) throws ProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NUM_DOCUMENTO = ? ORDER BY NUM_DOCUMENTO", new Object[] { numDocumento } );
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'NOMBRE_PROVEEDOR = :nombreProveedor'.
	 */
	public Proveedor[] findWhereNombreProveedorEquals(String nombreProveedor) throws ProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE NOMBRE_PROVEEDOR = ? ORDER BY NOMBRE_PROVEEDOR", new Object[] { nombreProveedor } );
	}

	/** 
	 * Returns all rows from the proveedor table that match the criteria 'CORREO = :correo'.
	 */
	public Proveedor[] findWhereCorreoEquals(String correo) throws ProveedorDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE CORREO = ? ORDER BY CORREO", new Object[] { correo } );
	}

	/**
	 * Method 'ProveedorDaoImpl'
	 * 
	 */
	public ProveedorDaoImpl()
	{
	}

	/**
	 * Method 'ProveedorDaoImpl'
	 * 
	 * @param userConn
	 */
	public ProveedorDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "tienda_online2.proveedor";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Proveedor fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Proveedor dto = new Proveedor();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Proveedor[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Proveedor dto = new Proveedor();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Proveedor ret[] = new Proveedor[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Proveedor dto, ResultSet rs) throws SQLException
	{
		dto.setTipoDocumentoTipoDocumento( rs.getString( COLUMN_TIPO_DOCUMENTO_TIPO_DOCUMENTO ) );
		dto.setNumDocumento( rs.getString( COLUMN_NUM_DOCUMENTO ) );
		dto.setNombreProveedor( rs.getString( COLUMN_NOMBRE_PROVEEDOR ) );
		dto.setCorreo( rs.getString( COLUMN_CORREO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Proveedor dto)
	{
	}

	/** 
	 * Returns all rows from the proveedor table that match the specified arbitrary SQL statement
	 */
	public Proveedor[] findByDynamicSelect(String sql, Object[] sqlParams) throws ProveedorDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the proveedor table that match the specified arbitrary SQL statement
	 */
	public Proveedor[] findByDynamicWhere(String sql, Object[] sqlParams) throws ProveedorDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new ProveedorDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
