/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.dto;

import edu.co.sena.ejemplodao.dao.*;
import edu.co.sena.ejemplodao.factory.*;
import edu.co.sena.ejemplodao.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Catalogo implements Serializable
{
	/** 
	 * This attribute maps to the column ID_CATALOGO in the catalogo table.
	 */
	protected int idCatalogo;

	/** 
	 * This attribute maps to the column NOMBRE_CATALOGO in the catalogo table.
	 */
	protected String nombreCatalogo;

	/** 
	 * This attribute maps to the column DESCRIPCION in the catalogo table.
	 */
	protected String descripcion;

	/**
	 * Method 'Catalogo'
	 * 
	 */
	public Catalogo()
	{
	}

	/**
	 * Method 'getIdCatalogo'
	 * 
	 * @return int
	 */
	public int getIdCatalogo()
	{
		return idCatalogo;
	}

	/**
	 * Method 'setIdCatalogo'
	 * 
	 * @param idCatalogo
	 */
	public void setIdCatalogo(int idCatalogo)
	{
		this.idCatalogo = idCatalogo;
	}

	/**
	 * Method 'getNombreCatalogo'
	 * 
	 * @return String
	 */
	public String getNombreCatalogo()
	{
		return nombreCatalogo;
	}

	/**
	 * Method 'setNombreCatalogo'
	 * 
	 * @param nombreCatalogo
	 */
	public void setNombreCatalogo(String nombreCatalogo)
	{
		this.nombreCatalogo = nombreCatalogo;
	}

	/**
	 * Method 'getDescripcion'
	 * 
	 * @return String
	 */
	public String getDescripcion()
	{
		return descripcion;
	}

	/**
	 * Method 'setDescripcion'
	 * 
	 * @param descripcion
	 */
	public void setDescripcion(String descripcion)
	{
		this.descripcion = descripcion;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Catalogo)) {
			return false;
		}
		
		final Catalogo _cast = (Catalogo) _other;
		if (idCatalogo != _cast.idCatalogo) {
			return false;
		}
		
		if (nombreCatalogo == null ? _cast.nombreCatalogo != nombreCatalogo : !nombreCatalogo.equals( _cast.nombreCatalogo )) {
			return false;
		}
		
		if (descripcion == null ? _cast.descripcion != descripcion : !descripcion.equals( _cast.descripcion )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idCatalogo;
		if (nombreCatalogo != null) {
			_hashCode = 29 * _hashCode + nombreCatalogo.hashCode();
		}
		
		if (descripcion != null) {
			_hashCode = 29 * _hashCode + descripcion.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return CatalogoPk
	 */
	public CatalogoPk createPk()
	{
		return new CatalogoPk(idCatalogo);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.dto.Catalogo: " );
		ret.append( "idCatalogo=" + idCatalogo );
		ret.append( ", nombreCatalogo=" + nombreCatalogo );
		ret.append( ", descripcion=" + descripcion );
		return ret.toString();
	}

}
