/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the cuenta table.
 */
public class CuentaPk implements Serializable
{
	protected String tipoDocumentoTipoDocumento;

	protected String numeroDocumento;

	/** 
	 * Sets the value of tipoDocumentoTipoDocumento
	 */
	public void setTipoDocumentoTipoDocumento(String tipoDocumentoTipoDocumento)
	{
		this.tipoDocumentoTipoDocumento = tipoDocumentoTipoDocumento;
	}

	/** 
	 * Gets the value of tipoDocumentoTipoDocumento
	 */
	public String getTipoDocumentoTipoDocumento()
	{
		return tipoDocumentoTipoDocumento;
	}

	/** 
	 * Sets the value of numeroDocumento
	 */
	public void setNumeroDocumento(String numeroDocumento)
	{
		this.numeroDocumento = numeroDocumento;
	}

	/** 
	 * Gets the value of numeroDocumento
	 */
	public String getNumeroDocumento()
	{
		return numeroDocumento;
	}

	/**
	 * Method 'CuentaPk'
	 * 
	 */
	public CuentaPk()
	{
	}

	/**
	 * Method 'CuentaPk'
	 * 
	 * @param tipoDocumentoTipoDocumento
	 * @param numeroDocumento
	 */
	public CuentaPk(final String tipoDocumentoTipoDocumento, final String numeroDocumento)
	{
		this.tipoDocumentoTipoDocumento = tipoDocumentoTipoDocumento;
		this.numeroDocumento = numeroDocumento;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof CuentaPk)) {
			return false;
		}
		
		final CuentaPk _cast = (CuentaPk) _other;
		if (tipoDocumentoTipoDocumento == null ? _cast.tipoDocumentoTipoDocumento != tipoDocumentoTipoDocumento : !tipoDocumentoTipoDocumento.equals( _cast.tipoDocumentoTipoDocumento )) {
			return false;
		}
		
		if (numeroDocumento == null ? _cast.numeroDocumento != numeroDocumento : !numeroDocumento.equals( _cast.numeroDocumento )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (tipoDocumentoTipoDocumento != null) {
			_hashCode = 29 * _hashCode + tipoDocumentoTipoDocumento.hashCode();
		}
		
		if (numeroDocumento != null) {
			_hashCode = 29 * _hashCode + numeroDocumento.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.dto.CuentaPk: " );
		ret.append( "tipoDocumentoTipoDocumento=" + tipoDocumentoTipoDocumento );
		ret.append( ", numeroDocumento=" + numeroDocumento );
		return ret.toString();
	}

}
