/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the departamento table.
 */
public class DepartamentoPk implements Serializable
{
	protected int idDepartamento;

	/** 
	 * This attribute represents whether the primitive attribute idDepartamento is null.
	 */
	protected boolean idDepartamentoNull;

	/** 
	 * Sets the value of idDepartamento
	 */
	public void setIdDepartamento(int idDepartamento)
	{
		this.idDepartamento = idDepartamento;
	}

	/** 
	 * Gets the value of idDepartamento
	 */
	public int getIdDepartamento()
	{
		return idDepartamento;
	}

	/**
	 * Method 'DepartamentoPk'
	 * 
	 */
	public DepartamentoPk()
	{
	}

	/**
	 * Method 'DepartamentoPk'
	 * 
	 * @param idDepartamento
	 */
	public DepartamentoPk(final int idDepartamento)
	{
		this.idDepartamento = idDepartamento;
	}

	/** 
	 * Sets the value of idDepartamentoNull
	 */
	public void setIdDepartamentoNull(boolean idDepartamentoNull)
	{
		this.idDepartamentoNull = idDepartamentoNull;
	}

	/** 
	 * Gets the value of idDepartamentoNull
	 */
	public boolean isIdDepartamentoNull()
	{
		return idDepartamentoNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DepartamentoPk)) {
			return false;
		}
		
		final DepartamentoPk _cast = (DepartamentoPk) _other;
		if (idDepartamento != _cast.idDepartamento) {
			return false;
		}
		
		if (idDepartamentoNull != _cast.idDepartamentoNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idDepartamento;
		_hashCode = 29 * _hashCode + (idDepartamentoNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.dto.DepartamentoPk: " );
		ret.append( "idDepartamento=" + idDepartamento );
		return ret.toString();
	}

}
