/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the domicilio_provee table.
 */
public class DomicilioProveePk implements Serializable
{
	protected String proveedorTipoDocumentoTipoDocumento;

	protected String proveedorNumDocumento;

	/** 
	 * Sets the value of proveedorTipoDocumentoTipoDocumento
	 */
	public void setProveedorTipoDocumentoTipoDocumento(String proveedorTipoDocumentoTipoDocumento)
	{
		this.proveedorTipoDocumentoTipoDocumento = proveedorTipoDocumentoTipoDocumento;
	}

	/** 
	 * Gets the value of proveedorTipoDocumentoTipoDocumento
	 */
	public String getProveedorTipoDocumentoTipoDocumento()
	{
		return proveedorTipoDocumentoTipoDocumento;
	}

	/** 
	 * Sets the value of proveedorNumDocumento
	 */
	public void setProveedorNumDocumento(String proveedorNumDocumento)
	{
		this.proveedorNumDocumento = proveedorNumDocumento;
	}

	/** 
	 * Gets the value of proveedorNumDocumento
	 */
	public String getProveedorNumDocumento()
	{
		return proveedorNumDocumento;
	}

	/**
	 * Method 'DomicilioProveePk'
	 * 
	 */
	public DomicilioProveePk()
	{
	}

	/**
	 * Method 'DomicilioProveePk'
	 * 
	 * @param proveedorTipoDocumentoTipoDocumento
	 * @param proveedorNumDocumento
	 */
	public DomicilioProveePk(final String proveedorTipoDocumentoTipoDocumento, final String proveedorNumDocumento)
	{
		this.proveedorTipoDocumentoTipoDocumento = proveedorTipoDocumentoTipoDocumento;
		this.proveedorNumDocumento = proveedorNumDocumento;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DomicilioProveePk)) {
			return false;
		}
		
		final DomicilioProveePk _cast = (DomicilioProveePk) _other;
		if (proveedorTipoDocumentoTipoDocumento == null ? _cast.proveedorTipoDocumentoTipoDocumento != proveedorTipoDocumentoTipoDocumento : !proveedorTipoDocumentoTipoDocumento.equals( _cast.proveedorTipoDocumentoTipoDocumento )) {
			return false;
		}
		
		if (proveedorNumDocumento == null ? _cast.proveedorNumDocumento != proveedorNumDocumento : !proveedorNumDocumento.equals( _cast.proveedorNumDocumento )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (proveedorTipoDocumentoTipoDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorTipoDocumentoTipoDocumento.hashCode();
		}
		
		if (proveedorNumDocumento != null) {
			_hashCode = 29 * _hashCode + proveedorNumDocumento.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.dto.DomicilioProveePk: " );
		ret.append( "proveedorTipoDocumentoTipoDocumento=" + proveedorTipoDocumentoTipoDocumento );
		ret.append( ", proveedorNumDocumento=" + proveedorNumDocumento );
		return ret.toString();
	}

}
