/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the factura table.
 */
public class FacturaPk implements Serializable
{
	protected int idFactura;

	/** 
	 * This attribute represents whether the primitive attribute idFactura is null.
	 */
	protected boolean idFacturaNull;

	/** 
	 * Sets the value of idFactura
	 */
	public void setIdFactura(int idFactura)
	{
		this.idFactura = idFactura;
	}

	/** 
	 * Gets the value of idFactura
	 */
	public int getIdFactura()
	{
		return idFactura;
	}

	/**
	 * Method 'FacturaPk'
	 * 
	 */
	public FacturaPk()
	{
	}

	/**
	 * Method 'FacturaPk'
	 * 
	 * @param idFactura
	 */
	public FacturaPk(final int idFactura)
	{
		this.idFactura = idFactura;
	}

	/** 
	 * Sets the value of idFacturaNull
	 */
	public void setIdFacturaNull(boolean idFacturaNull)
	{
		this.idFacturaNull = idFacturaNull;
	}

	/** 
	 * Gets the value of idFacturaNull
	 */
	public boolean isIdFacturaNull()
	{
		return idFacturaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof FacturaPk)) {
			return false;
		}
		
		final FacturaPk _cast = (FacturaPk) _other;
		if (idFactura != _cast.idFactura) {
			return false;
		}
		
		if (idFacturaNull != _cast.idFacturaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idFactura;
		_hashCode = 29 * _hashCode + (idFacturaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "edu.co.sena.ejemplodao.dto.FacturaPk: " );
		ret.append( "idFactura=" + idFactura );
		return ret.toString();
	}

}
