/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.dao;

import edu.co.sena.ejemplodao.dto.*;
import edu.co.sena.ejemplodao.exceptions.*;

public interface DepartamentoDao
{
	/** 
	 * Inserts a new row in the departamento table.
	 */
	public DepartamentoPk insert(Departamento dto) throws DepartamentoDaoException;

	/** 
	 * Updates a single row in the departamento table.
	 */
	public void update(DepartamentoPk pk, Departamento dto) throws DepartamentoDaoException;

	/** 
	 * Deletes a single row in the departamento table.
	 */
	public void delete(DepartamentoPk pk) throws DepartamentoDaoException;

	/** 
	 * Returns the rows from the departamento table that matches the specified primary-key value.
	 */
	public Departamento findByPrimaryKey(DepartamentoPk pk) throws DepartamentoDaoException;

	/** 
	 * Returns all rows from the departamento table that match the criteria 'ID_DEPARTAMENTO = :idDepartamento'.
	 */
	public Departamento findByPrimaryKey(int idDepartamento) throws DepartamentoDaoException;

	/** 
	 * Returns all rows from the departamento table that match the criteria ''.
	 */
	public Departamento[] findAll() throws DepartamentoDaoException;

	/** 
	 * Returns all rows from the departamento table that match the criteria 'ID_DEPARTAMENTO = :idDepartamento'.
	 */
	public Departamento[] findWhereIdDepartamentoEquals(int idDepartamento) throws DepartamentoDaoException;

	/** 
	 * Returns all rows from the departamento table that match the criteria 'NOMBRE_DEPARTAMENTO = :nombreDepartamento'.
	 */
	public Departamento[] findWhereNombreDepartamentoEquals(String nombreDepartamento) throws DepartamentoDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the departamento table that match the specified arbitrary SQL statement
	 */
	public Departamento[] findByDynamicSelect(String sql, Object[] sqlParams) throws DepartamentoDaoException;

	/** 
	 * Returns all rows from the departamento table that match the specified arbitrary SQL statement
	 */
	public Departamento[] findByDynamicWhere(String sql, Object[] sqlParams) throws DepartamentoDaoException;

}
