/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.dao;

import edu.co.sena.ejemplodao.dto.*;
import edu.co.sena.ejemplodao.exceptions.*;

public interface UsuarioDao
{
	/** 
	 * Inserts a new row in the usuario table.
	 */
	public UsuarioPk insert(Usuario dto) throws UsuarioDaoException;

	/** 
	 * Updates a single row in the usuario table.
	 */
	public void update(UsuarioPk pk, Usuario dto) throws UsuarioDaoException;

	/** 
	 * Deletes a single row in the usuario table.
	 */
	public void delete(UsuarioPk pk) throws UsuarioDaoException;

	/** 
	 * Returns the rows from the usuario table that matches the specified primary-key value.
	 */
	public Usuario findByPrimaryKey(UsuarioPk pk) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the usuario table that match the criteria 'ID_USUARIO = :idUsuario'.
	 */
	public Usuario findByPrimaryKey(String idUsuario) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the usuario table that match the criteria ''.
	 */
	public Usuario[] findAll() throws UsuarioDaoException;

	/** 
	 * Returns all rows from the usuario table that match the criteria 'ID_USUARIO = :idUsuario'.
	 */
	public Usuario[] findWhereIdUsuarioEquals(String idUsuario) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the usuario table that match the criteria 'PASSWORD = :password'.
	 */
	public Usuario[] findWherePasswordEquals(String password) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the usuario table that match the criteria 'ROL = :rol'.
	 */
	public Usuario[] findWhereRolEquals(String rol) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the usuario table that match the criteria 'ESTADO = :estado'.
	 */
	public Usuario[] findWhereEstadoEquals(String estado) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the usuario table that match the criteria 'CORREO_ELECTRONICO = :correoElectronico'.
	 */
	public Usuario[] findWhereCorreoElectronicoEquals(String correoElectronico) throws UsuarioDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the usuario table that match the specified arbitrary SQL statement
	 */
	public Usuario[] findByDynamicSelect(String sql, Object[] sqlParams) throws UsuarioDaoException;

	/** 
	 * Returns all rows from the usuario table that match the specified arbitrary SQL statement
	 */
	public Usuario[] findByDynamicWhere(String sql, Object[] sqlParams) throws UsuarioDaoException;

}
