/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.ejemplodao.dao.CuentaDao;
import edu.co.sena.ejemplodao.dto.Cuenta;
import edu.co.sena.ejemplodao.exceptions.CuentaDaoException;
import edu.co.sena.ejemplodao.factory.CuentaDaoFactory;

public class CuentaDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByTipoDocumento("");
		// findByUsuario("");
		// findWhereTipoDocumentoTipoDocumentoEquals("");
		// findWhereNumeroDocumentoEquals("");
		// findWherePrimerNombreEquals("");
		// findWhereSegunroNombreEquals("");
		// findWherePrimerApellidoEquals("");
		// findWhereSegundoApellidoEquals("");
		// findWhereUsuarioIdUsuarioEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByTipoDocumento'
	 * 
	 * @param tipoDocumentoTipoDocumento
	 */
	public static void findByTipoDocumento(String tipoDocumentoTipoDocumento)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findByTipoDocumento(tipoDocumentoTipoDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByUsuario'
	 * 
	 * @param usuarioIdUsuario
	 */
	public static void findByUsuario(String usuarioIdUsuario)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findByUsuario(usuarioIdUsuario);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereTipoDocumentoTipoDocumentoEquals'
	 * 
	 * @param tipoDocumentoTipoDocumento
	 */
	public static void findWhereTipoDocumentoTipoDocumentoEquals(String tipoDocumentoTipoDocumento)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereTipoDocumentoTipoDocumentoEquals(tipoDocumentoTipoDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNumeroDocumentoEquals'
	 * 
	 * @param numeroDocumento
	 */
	public static void findWhereNumeroDocumentoEquals(String numeroDocumento)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereNumeroDocumentoEquals(numeroDocumento);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePrimerNombreEquals'
	 * 
	 * @param primerNombre
	 */
	public static void findWherePrimerNombreEquals(String primerNombre)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWherePrimerNombreEquals(primerNombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSegunroNombreEquals'
	 * 
	 * @param segunroNombre
	 */
	public static void findWhereSegunroNombreEquals(String segunroNombre)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereSegunroNombreEquals(segunroNombre);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePrimerApellidoEquals'
	 * 
	 * @param primerApellido
	 */
	public static void findWherePrimerApellidoEquals(String primerApellido)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWherePrimerApellidoEquals(primerApellido);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereSegundoApellidoEquals'
	 * 
	 * @param segundoApellido
	 */
	public static void findWhereSegundoApellidoEquals(String segundoApellido)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereSegundoApellidoEquals(segundoApellido);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereUsuarioIdUsuarioEquals'
	 * 
	 * @param usuarioIdUsuario
	 */
	public static void findWhereUsuarioIdUsuarioEquals(String usuarioIdUsuario)
	{
		try {
			CuentaDao _dao = getCuentaDao();
			Cuenta _result[] = _dao.findWhereUsuarioIdUsuarioEquals(usuarioIdUsuario);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getCuentaDao'
	 * 
	 * @return CuentaDao
	 */
	public static CuentaDao getCuentaDao()
	{
		return CuentaDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Cuenta dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getTipoDocumentoTipoDocumento() );
		buf.append( ", " );
		buf.append( dto.getNumeroDocumento() );
		buf.append( ", " );
		buf.append( dto.getPrimerNombre() );
		buf.append( ", " );
		buf.append( dto.getSegunroNombre() );
		buf.append( ", " );
		buf.append( dto.getPrimerApellido() );
		buf.append( ", " );
		buf.append( dto.getSegundoApellido() );
		buf.append( ", " );
		buf.append( dto.getUsuarioIdUsuario() );
		System.out.println( buf.toString() );
	}

}
