/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import edu.co.sena.ejemplodao.dao.ProductoDao;
import edu.co.sena.ejemplodao.dto.Producto;
import edu.co.sena.ejemplodao.exceptions.ProductoDaoException;
import edu.co.sena.ejemplodao.factory.ProductoDaoFactory;

public class ProductoDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findByCatalogo(0);
		// findByCategoria(0);
		// findWhereIdProductoEquals("");
		// findWhereNombreProductoEquals("");
		// findWherePrecioDetalEquals(0);
		// findWhereImagenEquals(null);
		// findWhereCantidadEquals(0);
		// findWhereActivoEquals(0);
		// findWhereCategoriaIdCategoriaEquals(0);
		// findWhereCatalogoIdCatalogoEquals(0);
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ProductoDao _dao = getProductoDao();
			Producto _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByCatalogo'
	 * 
	 * @param catalogoIdCatalogo
	 */
	public static void findByCatalogo(int catalogoIdCatalogo)
	{
		try {
			ProductoDao _dao = getProductoDao();
			Producto _result[] = _dao.findByCatalogo(catalogoIdCatalogo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findByCategoria'
	 * 
	 * @param categoriaIdCategoria
	 */
	public static void findByCategoria(int categoriaIdCategoria)
	{
		try {
			ProductoDao _dao = getProductoDao();
			Producto _result[] = _dao.findByCategoria(categoriaIdCategoria);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdProductoEquals'
	 * 
	 * @param idProducto
	 */
	public static void findWhereIdProductoEquals(String idProducto)
	{
		try {
			ProductoDao _dao = getProductoDao();
			Producto _result[] = _dao.findWhereIdProductoEquals(idProducto);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereNombreProductoEquals'
	 * 
	 * @param nombreProducto
	 */
	public static void findWhereNombreProductoEquals(String nombreProducto)
	{
		try {
			ProductoDao _dao = getProductoDao();
			Producto _result[] = _dao.findWhereNombreProductoEquals(nombreProducto);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWherePrecioDetalEquals'
	 * 
	 * @param precioDetal
	 */
	public static void findWherePrecioDetalEquals(double precioDetal)
	{
		try {
			ProductoDao _dao = getProductoDao();
			Producto _result[] = _dao.findWherePrecioDetalEquals(precioDetal);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereImagenEquals'
	 * 
	 * @param imagen
	 */
	public static void findWhereImagenEquals(byte[] imagen)
	{
		try {
			ProductoDao _dao = getProductoDao();
			Producto _result[] = _dao.findWhereImagenEquals(imagen);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCantidadEquals'
	 * 
	 * @param cantidad
	 */
	public static void findWhereCantidadEquals(float cantidad)
	{
		try {
			ProductoDao _dao = getProductoDao();
			Producto _result[] = _dao.findWhereCantidadEquals(cantidad);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereActivoEquals'
	 * 
	 * @param activo
	 */
	public static void findWhereActivoEquals(short activo)
	{
		try {
			ProductoDao _dao = getProductoDao();
			Producto _result[] = _dao.findWhereActivoEquals(activo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCategoriaIdCategoriaEquals'
	 * 
	 * @param categoriaIdCategoria
	 */
	public static void findWhereCategoriaIdCategoriaEquals(int categoriaIdCategoria)
	{
		try {
			ProductoDao _dao = getProductoDao();
			Producto _result[] = _dao.findWhereCategoriaIdCategoriaEquals(categoriaIdCategoria);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereCatalogoIdCatalogoEquals'
	 * 
	 * @param catalogoIdCatalogo
	 */
	public static void findWhereCatalogoIdCatalogoEquals(int catalogoIdCatalogo)
	{
		try {
			ProductoDao _dao = getProductoDao();
			Producto _result[] = _dao.findWhereCatalogoIdCatalogoEquals(catalogoIdCatalogo);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getProductoDao'
	 * 
	 * @return ProductoDao
	 */
	public static ProductoDao getProductoDao()
	{
		return ProductoDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Producto dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdProducto() );
		buf.append( ", " );
		buf.append( dto.getNombreProducto() );
		buf.append( ", " );
		buf.append( dto.getPrecioDetal() );
		buf.append( ", " );
		buf.append( dto.getImagen() );
		buf.append( ", " );
		buf.append( dto.getCantidad() );
		buf.append( ", " );
		buf.append( dto.getActivo() );
		buf.append( ", " );
		buf.append( dto.getCategoriaIdCategoria() );
		buf.append( ", " );
		buf.append( dto.getCatalogoIdCatalogo() );
		System.out.println( buf.toString() );
	}

}
