/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package edu.co.sena.ejemplodao.exceptions;

public class DepartamentoDaoException extends DaoException
{
	/**
	 * Method 'DepartamentoDaoException'
	 * 
	 * @param message
	 */
	public DepartamentoDaoException(String message)
	{
		super(message);
	}

	/**
	 * Method 'DepartamentoDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public DepartamentoDaoException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
